export const chaptersData = {
  "6.Science":["Materials Around Us",
      "Temperature and its Measurement",
      "A Journey through States of Water",
      "Methods of Separation in Everyday Life",
      "Living Creatures: Exploring their Characteristics",
      "Nature’s Treasures",
      "Beyond Earth"
  ],
  "11.Biology": [
      "All Chapters",
      "The Living World",
      "Biological Classification",
      "Plant Kingdom",
      "Animal Kingdom",
      "Morphology of Flowering Plants",
      "Anatomy of Flowering Plants",
      "Structural Organisation in Animals",
      "Cell: The Unit of Life",
      "Biomolecules",
      "Cell Cycle and Cell Division",
      "Transport in Plants",
      "Mineral Nutrition",
      "Photosynthesis in Higher Plants",
      "Respiration in Plants",
      "Plant Growth and Development",
      "Digestion and Absorption",
      "Breathing and Exchange of Gases",
      "Body Fluids and Circulation",
      "Excretory Products and their Elimination",
      "Locomotion and Movement",
      "Neural Control and Coordination",
      "Chemical Coordination and Integration"
    ]
    ,
  "11.Physics": ["Kinematics", "Laws of Motion", "Thermodynamics"],
  "11.Chemistry": ["Atomic Structure", "Chemical Bonding", "Thermodynamics"],
  "11.Economics" : ["Concept of cost", "concept of revenue", "producer equilibrium","theory of supply", "collection of data","census and sampal method of collection of data","presentation of data textual and tabular presentation","diagrammatic presentation of data bar diagrams and pie diagram"],
  "12.Biology": [
      "All Chapters",
      "Reproduction",
      "Sexual Reproduction in Flowering Plants",
      "Human Reproduction",
      "Reproductive Health",
      "Principles of Inheritance and Variation",
      "Molecular Basis of Inheritance",
      "Evolution",
      "Human Health and Disease",
      "Strategies for Enhancement in Food Production",
      "Microbes in Human Welfare",
      "Biotechnology: Principles and Processes",
      "Biotechnology and its Applications",
      "Organisms and Populations",
      "Ecosystem",
      "Biodiversity and Conservation",
      "Environmental Issues"
    ]
    ,
  "12.Physics": ["Electrostatics", "Magnetism", "Optics"],
  "12.Chemistry": ["Solid State", "Electrochemistry", "Coordination Compounds"],
};
